services:
  backend:
    image: backend:e-commerce
    container_name: e-commerce-backend
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password.txt
      - DB_USER=postgres
      - DB_HOST=e-commerce-db
      - DB_PORT=5432
      - DB_NAME=ecommerce
      - DB_SCHEMA=public
      - CORS_ALLOW_ORIGIN='https://angular-e-commerce.localhost https://e-commerce.localhost'
    volumes:
      # - /etc/app1/secrets:/run/secrets:ro
      - ./secrets/ecom_db_password.txt:/run/secrets/db_password.txt:ro
    networks:
      - e-commerce-net
      - proxy-net
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: e-commerce-db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password.txt
    volumes:
      - ecomm:/var/lib/postgresql/data
      # - /etc/app1/secrets:/run/secrets:ro
      - ../../secrets/ecom_db_password.txt:/run/secrets/db_password.txt:ro
    networks:
      - e-commerce-net

volumes:
  ecomm:

networks:
  e-commerce-net:
  proxy-net:
    external: true
