
server {
    listen 80;
    listen [::]:80;
    server_name gw2-armory;

    # location /.well-known/acme-challenge/ {
    # root /var/www/certbot;
    # }

    location / {
        return 301 https://$host$request_uri;
    }

}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name  gw2-armory.com;
    root /var/www/armory/dist;

    ssl_certificate /etc/letsencrypt/live/gw2-armory.crt; 
    ssl_certificate_key /etc/letsencrypt/live/gw2-armory.key;
    ssl_trusted_certificate /etc/letsencrypt/live/gw2-armory.pem;
    add_header Strict-Transport-Security "max-age=63072000" always;

    location / {
        index index.html;
        try_files $uri /index.html;
    }

    location /api/ {       
        proxy_pass http://armory-backend:8000/; 
        
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;  
    }

}

