#cloud-config

groups:
  - ubuntu: [root, sys]
  - hashicorp

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuo4HKpYZCLH5MHj9j8p76M/WyDieM8T9i0mXePRgHj zoemhay@gmail.com

write_files:
  - path: /usr/local/bin/init.sh
    permissions: "0755"
    owner: "root:root"
    content: |
      ${init_script}

runcmd:
  - sudo su terraform
  - echo "scripts copied to opt/scripts"
