services:
  nginx:
    image: nginx:local-nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./conf:/etc/nginx/conf.d:ro
      # - ./certs:/etc/ssl/certs:ro
      - ./local-certs/certs:/etc/letsencrypt/live:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
